# Generated by Django 5.2.3 on 2025-07-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Macho'), ('female', 'Hembra')], max_length=10)),
                ('size', models.CharField(choices=[('small', 'Pequeño'), ('medium', 'Mediano'), ('large', 'Grande')], max_length=20)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('health_status', models.CharField(choices=[('healthy', 'Saludable'), ('needs healthcare attention', 'Necesita cuidados')], max_length=50)),
                ('vaccinated', models.BooleanField(default=False)),
                ('adoption_status', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reservado'), ('adopted', 'Adoptado')], default='available', max_length=10)),
                ('temper', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
